### ISSUE TITLE
[Frontend | FEAT] 프레임 생성 및 연습 : Mobile

### ISSUE THREAD

**Issue by Jhcki222** [CSID-DGU/2023-2-OSSP1-WantToGraduateTeam-8#12]
## :loudspeaker: 이슈 내용
> 프레임 생성 및 연습
## :page_with_curl: 상세 내용
- 프런트엔드 멤버 프레임 생성 및 연습을 위한 브랜치 생성
## :heavy_check_mark: 체크리스트
- [x] todo
- [x] todo

**Comment by sudden11y** [comment]
마이페이지(Mypage) 프레임 초기 형성 완료
